### PR TITLE
Upgrade to 2.1.1 (edit: 2.1.2)

### PR DESCRIPTION
**Pull request by lllleonnnn**
Currently getting recovery errors along these lines:
https://github.com/elastic/elasticsearch/issues/14989

That may eventually cause the space to fill up unnecessarily.

Can we bump versions? @cameronmaske 

If you say yes I will open PR

### CODE REVIEW

**Comment by lllleonnnn** [comment]
@cameronmaske some silly gotchas with this one:
- Needed to add `echo  >> $ES_CFG_FILE` to 2.1.2's `run` file to avoid this error which appended lines to the config without a newline:

```
$ docker run --publish 9212:9200  --env ES_NETWORK_BIND__HOST=0.0.0.0 --env ES_CLUSTER_NAME=hello --env ES_NODE_NAME=test quay.io/trackmaven/elasticsearch:2.1.2

Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: ScannerException[mapping values are not allowed here
 in 'reader', line 32, column 53:
     ... ulticast.enabled: falsenode.name: test
```
- Added a `--fix-missing` to the `RUN apt-get update` across all Dockerfiles to address this caching mismatch error:

```
Step 13 : RUN apt-get update
 ---> Running in 468f4ac6f3af
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [272 kB]
Ign http://httpredir.debian.org jessie InRelease
Get:3 http://httpredir.debian.org jessie-updates InRelease [142 kB]
Get:4 http://httpredir.debian.org jessie-backports InRelease [166 kB]
Get:5 http://httpredir.debian.org jessie Release.gpg [2373 B]
Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [5019 B]
Get:7 http://httpredir.debian.org jessie-backports/main amd64 Packages [572 kB]
Get:8 http://httpredir.debian.org jessie Release [148 kB]
Get:9 http://httpredir.debian.org jessie/main amd64 Packages [9034 kB]
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
Fetched 10.4 MB in 1s (5453 kB/s)

docker build -t quay.io/trackmaven/elasticsearch:2.1.2 2.1.2 returned exit code 1

The command '/bin/sh -c apt-get update' returned a non-zero code: 100 Action failed: docker build -t quay.io/trackmaven/elasticsearch:2.1.2 2.1.2
```

which happened at one point or another with all versions (1.7, 2.1, 2.1.2) when testing locally or with CircleCI.

`release.sh` has been run, which I now realize should have waited until after the merge:
screen shot 2016-03-06 at 1 33 05 pm

## Request: merge or comment for change

**Comment by cameronmaske** [comment]
Hey @nowfred, I think should 2.1.2 just super seed over 2.1 (e.g. replace the current 2.1 install with 2.1.2). That fits with the major and minor version match.
We should change the deploy script to release the PATCH version as a seperate tag thou. 

Do those changes make sense?

**Comment by lllleonnnn** [comment]
@cameronmaske not really? what do you mean by deploy script? `release.sh` is updated to tag `2.1.2` separately

Are you saying have capability to just add a PATCH variable to enable easily updating patched versions of 2.1?

**Comment by lllleonnnn** [comment]
@cameronmaske what do you want to do with this? I don't understand what you mean about the PATCH as a separate tag but replace the `2.1` release

**Comment by cameronmaske** [comment]
@nowfred Hey Fred, I don't think I was very clear about how to structure the stuff. I pushed #9 which was a copy pasta job of what you did here. e.g. 2.1.2 should be live now!

**Comment by lllleonnnn** [comment]
:+1:

**Pull request closed without merging**
